# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player.proto',
  package='protblog',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0cplayer.proto\x12\x08protblog\"\xa7\x01\n\x0bPlayersList\x12,\n\x06player\x18\x01 \x03(\x0b\x32\x1c.protblog.PlayersList.Player\x1aj\n\x06Player\x12\x10\n\x08nickname\x18\x01 \x02(\t\x12\r\n\x05\x65mail\x18\x02 \x02(\t\x12\x15\n\rdate_of_birth\x18\x03 \x02(\t\x12\n\n\x02xp\x18\x04 \x02(\x05\x12\x1c\n\x03\x63ls\x18\x05 \x02(\x0e\x32\x0f.protblog.Class*5\n\x05\x43lass\x12\x0b\n\x07\x42\x65rserk\x10\x00\x12\x08\n\x04Tank\x10\x01\x12\x0b\n\x07Paladin\x10\x03\x12\x08\n\x04Mage\x10\x04')
)

_CLASS = _descriptor.EnumDescriptor(
  name='Class',
  full_name='protblog.Class',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Berserk', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Tank', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Paladin', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mage', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=196,
  serialized_end=249,
)
_sym_db.RegisterEnumDescriptor(_CLASS)

Class = enum_type_wrapper.EnumTypeWrapper(_CLASS)
Berserk = 0
Tank = 1
Paladin = 3
Mage = 4



_PLAYERSLIST_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='protblog.PlayersList.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='protblog.PlayersList.Player.nickname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='protblog.PlayersList.Player.email', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_of_birth', full_name='protblog.PlayersList.Player.date_of_birth', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xp', full_name='protblog.PlayersList.Player.xp', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cls', full_name='protblog.PlayersList.Player.cls', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=194,
)

_PLAYERSLIST = _descriptor.Descriptor(
  name='PlayersList',
  full_name='protblog.PlayersList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='protblog.PlayersList.player', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PLAYERSLIST_PLAYER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=194,
)

_PLAYERSLIST_PLAYER.fields_by_name['cls'].enum_type = _CLASS
_PLAYERSLIST_PLAYER.containing_type = _PLAYERSLIST
_PLAYERSLIST.fields_by_name['player'].message_type = _PLAYERSLIST_PLAYER
DESCRIPTOR.message_types_by_name['PlayersList'] = _PLAYERSLIST
DESCRIPTOR.enum_types_by_name['Class'] = _CLASS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayersList = _reflection.GeneratedProtocolMessageType('PlayersList', (_message.Message,), dict(

  Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERSLIST_PLAYER,
    __module__ = 'player_pb2'
    # @@protoc_insertion_point(class_scope:protblog.PlayersList.Player)
    ))
  ,
  DESCRIPTOR = _PLAYERSLIST,
  __module__ = 'player_pb2'
  # @@protoc_insertion_point(class_scope:protblog.PlayersList)
  ))
_sym_db.RegisterMessage(PlayersList)
_sym_db.RegisterMessage(PlayersList.Player)


# @@protoc_insertion_point(module_scope)
